<#
.SYNOPSIS
  Set up chrome-devtools-mcp as a long-lived HTTP service shared by every
  Claude Code session on this machine.

.DESCRIPTION
  Configures a Windows Scheduled Task that launches the fork's MCP server
  with --http-port at logon, restarts on failure, and binds to 127.0.0.1
  only. Generates a bearer token, stores it under %APPDATA%\cdmcp\token,
  and rewrites the chrome-devtools entry in the Claude Code user MCP
  config to point at the HTTP endpoint.

  Idempotent: safe to re-run to update settings.

.PARAMETER Port
  TCP port to bind on 127.0.0.1. Default 9876.

.PARAMETER ForkPath
  Path to the cloned chrome-devtools-mcp fork repo. Must already be built
  (`npm run build`).

.PARAMETER Force
  Recreate the token even if one already exists.

.EXAMPLE
  .\scripts\setup-shared-mcp.ps1

.EXAMPLE
  .\scripts\setup-shared-mcp.ps1 -Port 9000 -Force
#>
param(
    [int]$Port = 9876,
    [string]$ForkPath = '',
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

if (-not $ForkPath) {
    if ($PSScriptRoot) {
        $ForkPath = Split-Path -Parent $PSScriptRoot
    } else {
        $ForkPath = 'C:\Users\cejor\Dev\chrome-devtools-mcp'
    }
}
$ForkPath = (Resolve-Path -LiteralPath $ForkPath).Path

$ConfigDir   = Join-Path $env:APPDATA 'cdmcp'
$TokenFile   = Join-Path $ConfigDir 'token'
$LauncherFile = Join-Path $ConfigDir 'launcher.ps1'
$LogDir      = Join-Path $env:LOCALAPPDATA 'cdmcp\logs'
$ProfileDir  = Join-Path $env:LOCALAPPDATA 'cdmcp\chrome-profile'
$TaskName    = 'ChromeDevToolsMcpShared'

Write-Host '=== Chrome DevTools MCP — Shared HTTP Setup ===' -ForegroundColor Cyan
Write-Host ''

# --- 1. Verify the fork is built ---------------------------------------------
$cdmcpJs = Join-Path $ForkPath 'build\src\bin\chrome-devtools-mcp.js'
if (-not (Test-Path $cdmcpJs)) {
    throw "Fork build not found at $cdmcpJs. Run ``npm run build`` in $ForkPath first."
}
Write-Host "Fork build:      $cdmcpJs"

# --- 2. Ensure directories exist ---------------------------------------------
foreach ($dir in @($ConfigDir, $LogDir, $ProfileDir)) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}

# --- 3. Generate or reuse token ---------------------------------------------
if ((Test-Path $TokenFile) -and (-not $Force)) {
    $token = (Get-Content $TokenFile -Raw).Trim()
    Write-Host "Token:           reused existing ($TokenFile)"
} else {
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $token = -join ($bytes | ForEach-Object { '{0:x2}' -f $_ })

    [System.IO.File]::WriteAllText($TokenFile, $token, [System.Text.UTF8Encoding]::new($false))

    # Restrict ACL to current user only.
    $acl = Get-Acl $TokenFile
    $acl.SetAccessRuleProtection($true, $false)
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        "$env:USERDOMAIN\$env:USERNAME", 'FullControl', 'Allow'
    )
    $acl.SetAccessRule($rule)
    Set-Acl $TokenFile $acl

    Write-Host "Token:           generated ($TokenFile)"
}

# --- 4. Write launcher script -----------------------------------------------
# We embed paths via single-quoted strings so PowerShell doesn't interpret
# $-variables in them. The launcher reads the token at run time.
$launcher = @"
# Auto-generated by setup-shared-mcp.ps1. Do not edit by hand.
`$ErrorActionPreference = 'Stop'
`$token = (Get-Content '$TokenFile' -Raw).Trim()
`$logFile = Join-Path '$LogDir' ("server-" + (Get-Date -Format 'yyyyMMdd') + ".log")
`$env:CHROME_DEVTOOLS_MCP_NO_USAGE_STATISTICS = 'true'
& node '$cdmcpJs' ``
    --experimentalPageIdRouting ``
    --http-port $Port ``
    --http-host 127.0.0.1 ``
    --http-token `$token ``
    --user-data-dir '$ProfileDir' ``
    *>> `$logFile
"@
$launcher | Out-File -Encoding utf8 -FilePath $LauncherFile -Force
Write-Host "Launcher:        $LauncherFile"

# --- 5. Register the Scheduled Task ------------------------------------------
$action = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$LauncherFile`""

$trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"

$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -MultipleInstances IgnoreNew

$principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Limited

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}
Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description 'chrome-devtools-mcp shared HTTP server (cejor6 fork)' | Out-Null
Write-Host "Scheduled Task:  $TaskName (registered)"

# --- 6. Stop any prior instance and start fresh ------------------------------
try { Stop-ScheduledTask -TaskName $TaskName -ErrorAction Stop } catch {}
Start-ScheduledTask -TaskName $TaskName
Write-Host "Scheduled Task:  started"

# --- 7. Wait for the server to respond ---------------------------------------
$serverReady = $false
for ($i = 0; $i -lt 60; $i++) {
    try {
        $null = Invoke-WebRequest `
            -Uri "http://127.0.0.1:$Port/mcp" `
            -Method POST `
            -Headers @{ 'Authorization' = "Bearer $token"; 'Content-Type' = 'application/json' } `
            -Body '{}' `
            -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
        $serverReady = $true
        break
    } catch [System.Net.WebException] {
        # 4xx means server is reachable (just rejecting our malformed body).
        $status = $_.Exception.Response.StatusCode.Value__
        if ($status -ge 400 -and $status -lt 500) {
            $serverReady = $true
            break
        }
        Start-Sleep -Milliseconds 500
    } catch [Microsoft.PowerShell.Commands.HttpResponseException] {
        $status = $_.Exception.Response.StatusCode.Value__
        if ($status -ge 400 -and $status -lt 500) {
            $serverReady = $true
            break
        }
        Start-Sleep -Milliseconds 500
    } catch {
        Start-Sleep -Milliseconds 500
    }
}
if (-not $serverReady) {
    throw "Server did not become reachable on http://127.0.0.1:$Port within 30 seconds. Check the log at $LogDir."
}
Write-Host "HTTP endpoint:   http://127.0.0.1:$Port/mcp (reachable)"

# --- 8. Update Claude Code MCP config ----------------------------------------
& claude mcp remove chrome-devtools --scope user 2>$null | Out-Null
& claude mcp add chrome-devtools `
    --scope user `
    --transport http `
    --header "Authorization: Bearer $token" `
    "http://127.0.0.1:$Port/mcp"

if ($LASTEXITCODE -ne 0) {
    throw "claude mcp add failed."
}
Write-Host "Claude Code:     chrome-devtools entry rewritten to HTTP"

# --- 9. Summary --------------------------------------------------------------
Write-Host ''
Write-Host '=== Setup complete ===' -ForegroundColor Green
Write-Host ''
Write-Host '  Endpoint:        http://127.0.0.1:{0}/mcp' -f $Port
Write-Host "  Token file:      $TokenFile"
Write-Host "  Profile dir:     $ProfileDir"
Write-Host "  Logs:            $LogDir"
Write-Host "  Scheduled Task:  $TaskName"
Write-Host ''
Write-Host 'Restart any open Claude Code windows to pick up the new config.'
Write-Host 'To uninstall:  .\scripts\uninstall-shared-mcp.ps1'
