name: Check code format

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-format:
    runs-on: ubuntu-latest # You can also use 'macos-latest' or 'windows-latest'

    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          cache: npm
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Run format check
        run: npm run check-format
